[phases.setup]
nixPkgs = ['nodejs_20', 'npm-10_x', 'openssl']

[phases.install]
cmds = [
  'npm ci',
  'npx prisma generate'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'npm start'

[variables]
NIXPACKS_METADATA = "nodejs,prisma"