#!/bin/bash

echo "🗄️  Setting up Railway PostgreSQL Database"
echo "=========================================="
echo ""

echo "Step 1: Ensure PostgreSQL service exists"
echo "----------------------------------------"
echo "Run: railway add postgresql"
echo "   (If you haven't added PostgreSQL service yet)"
echo ""

echo "Step 2: Link to your web service"
echo "--------------------------------"
echo "Run: railway link"
echo "   Select: nine-nine-nine project"
echo "   Select: web service (your Next.js app)"
echo ""

echo "Step 3: Create initial migration"
echo "-------------------------------"
echo "railway run 'npx prisma migrate dev --name init'"
echo "   (Creates your database schema from prisma/schema.prisma)"
echo ""

echo "Step 4: Deploy migrations to production"
echo "-------------------------------------"
echo "railway run 'npx prisma migrate deploy'"
echo "   (Applies migrations to Railway PostgreSQL)"
echo ""

echo "Step 5: Generate Prisma client"
echo "-----------------------------"
echo "railway run 'npx prisma generate'"
echo "   (Generates TypeScript client for your schema)"
echo ""

echo "Step 6: Verify database setup"
echo "----------------------------"
echo "railway run 'npx prisma studio'"
echo "   (Opens Prisma Studio to view your database)"
echo ""

echo "🔧 Troubleshooting Commands:"
echo "----------------------------"
echo ""
echo "View database connection:"
echo "railway variables | grep DATABASE_URL"
echo ""
echo "Check database logs:"
echo "railway logs --service postgresql"
echo ""
echo "Reset database (if needed):"
echo "railway run 'npx prisma migrate reset --force'"
echo ""
echo "Manual database connection:"
echo "railway connect postgresql"
echo ""

echo "📋 Your Prisma Schema includes:"
echo "- Users (with Stytch integration)"
echo "- Events (with join codes)"
echo "- EventParticipants"
echo "- HoleScores (golf scores)"
echo "- MediaUploads (R2 photos/videos)"
echo "- Kudos (spectator recognition)"
echo ""

echo "🎯 After setup, test your app:"
echo "railway run npm run dev"
echo ""

echo "Or deploy to production:"
echo "railway up"